#!/usr/bin/env bash
# Regenerate the committed runtime dependency lock deterministically.
#
# The lock is pinned to a fixed package-index instant (EXCLUDE_NEWER) and
# resolved universally so it is byte-for-byte reproducible on every platform and
# at any future date. To intentionally pull in newer dependency versions, bump
# EXCLUDE_NEWER here and in scripts/validate_dependency_lock.sh to the same
# value, then run this script and commit the result.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REQUIREMENTS="runner/requirements.txt"
LOCKFILE="runner/requirements.lock.txt"
EXCLUDE_NEWER="${EXCLUDE_NEWER:-2026-05-29T00:00:00Z}"
UV_PIN="${UV_PIN:-0.11.17}"
PYTHON_TARGET="${PYTHON_TARGET:-3.11}"

# Resolve into a fresh temp file rather than overwriting $LOCKFILE in place.
# `uv pip compile -o <existing>` reuses the existing pins as resolution
# preferences, which would silently preserve stale transitive versions. A clean
# target forces a from-scratch resolution at the frozen index instant, so the
# committed lock equals what scripts/validate_dependency_lock.sh recomputes.
# Run from the repo root with a repo-relative requirements path so the lock's
# "# via -r <path>" annotations stay portable across machines and CI.
cd "$ROOT"
TMP_LOCK="$(mktemp)"
trap 'rm -f "$TMP_LOCK"' EXIT
uvx --from "uv==$UV_PIN" uv pip compile --python-version "$PYTHON_TARGET" "$REQUIREMENTS" --universal --generate-hashes \
  --exclude-newer "$EXCLUDE_NEWER" -o "$TMP_LOCK"
# Rewrite the autogenerated header's "-o <tmp>" back to the canonical lockfile
# path so the committed file does not record a throwaway temp path.
sed -E "s| -o [^ ]+\$| -o ${LOCKFILE}|" "$TMP_LOCK" > "$LOCKFILE"
rm -f "$TMP_LOCK"
trap - EXIT

echo "Wrote $LOCKFILE (index frozen at $EXCLUDE_NEWER)"
