#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REQUIREMENTS="runner/requirements.txt"
LOCKFILE="runner/requirements.lock.txt"
TEMP_ROOT="$(mktemp -d)"

# Pin the package index to a fixed instant so `uv pip compile` resolves the same
# versions on every platform and at any future date. Without this, an
# unconstrained recompile floats transitive dependencies to whatever PyPI
# publishes next, making the lock drift (and the gate fail) over time and across
# macOS/Linux. --universal produces a platform-independent lock that validates
# identically everywhere. To intentionally refresh the lock, bump this date and
# regenerate (see scripts/regenerate_dependency_lock.sh).
EXCLUDE_NEWER="${EXCLUDE_NEWER:-2026-05-29T00:00:00Z}"
UV_PIN="${UV_PIN:-0.11.17}"
PYTHON_TARGET="${PYTHON_TARGET:-3.11}"

cleanup() {
  rm -rf "$TEMP_ROOT"
}
trap cleanup EXIT

# Collapse the autogenerated "uv pip compile ..." command comment to a constant
# so the committed and freshly generated locks compare equal regardless of which
# flags or paths were used to produce them.
normalize_header() {
  sed -E -e 's|^#[[:space:]]*uv pip compile .*|#    uv pip compile <normalized>|'
}

# Run from the repo root with a repo-relative requirements path so the lock's
# "# via -r <path>" annotations stay portable (no absolute or username-specific
# paths baked into the committed file) and identical across machines and CI.
cd "$ROOT"
uvx --from "uv==$UV_PIN" uv pip compile --python-version "$PYTHON_TARGET" "$REQUIREMENTS" --universal --generate-hashes \
  --exclude-newer "$EXCLUDE_NEWER" -o "$TEMP_ROOT/requirements.lock.txt" >/dev/null
normalize_header < "$LOCKFILE" > "$TEMP_ROOT/committed.normalized"
normalize_header < "$TEMP_ROOT/requirements.lock.txt" > "$TEMP_ROOT/generated.normalized"
diff -u "$TEMP_ROOT/committed.normalized" "$TEMP_ROOT/generated.normalized"

uv run --with-requirements "$LOCKFILE" --with pip-audit pip-audit

echo "Runtime dependency lock: valid"
